name: instantgram
description: "An Instagram clone app using Riverpod state management framework in Vandad's riverpod's course"
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.14.0
  firebase_auth: ^4.15.0
  cloud_firestore: ^4.13.3
  uuid: ^4.2.1
  hooks_riverpod: ^2.4.9
  firebase_storage: ^11.5.3
  image_picker: ^1.0.4
  image: ^4.1.3
  google_sign_in: ^6.1.6
  flutter_facebook_auth: ^6.0.3
  flutter_hooks: ^0.20.3
  collection: ^1.18.0
  intl: ^0.18.1
  video_thumbnail: ^0.5.3
  video_player: ^2.8.1
  lottie: ^2.7.0
  share_plus: ^7.2.1
  url_launcher: ^6.2.1
  activout_firebase_options_selector: ^1.0.0
  font_awesome_flutter: ^10.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/animations/empty.json
    - assets/animations/error.json
    - assets/animations/loading.json
    - assets/animations/small_error.json
    - assets/animations/data_not_found.json



  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
